name: vasttrafik_nara
description: Another Västtrafik travel planner

publish_to: 'none'

version: 2.0.18+18

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_typeahead: ^4.1.0
  device_info_plus: ^4.1.2
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
