name: vasttrafik_nara
description: Another Västtrafik travel planner

publish_to: 'none'

version: 2.0.20+20

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_typeahead: ^4.1.0
  device_info_plus: ^4.1.2
  geolocator: ^9.0.1
  icons_launcher: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: 'assets/app_icon.png'
  platforms:
    macos:
      enable: true
      image_path: 'assets/mac_app_icon.png'
